/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* idleInt */
#define idleInt__INTC_CORTEXM4_ASSIGNED 1
#define idleInt__INTC_CORTEXM4_PRIORITY 6u
#define idleInt__INTC_NUMBER 122u
#define idleInt_INTC_CORTEXM4_ASSIGNED 1
#define idleInt_INTC_CORTEXM4_PRIORITY 6u
#define idleInt_INTC_NUMBER 122u

/* isr_timer */
#define isr_timer__INTC_CORTEXM4_ASSIGNED 1
#define isr_timer__INTC_CORTEXM4_PRIORITY 7u
#define isr_timer__INTC_NUMBER 123u
#define isr_timer_INTC_CORTEXM4_ASSIGNED 1
#define isr_timer_INTC_CORTEXM4_PRIORITY 7u
#define isr_timer_INTC_NUMBER 123u

/* sampleEvent */
#define sampleEvent__INTC_CORTEXM4_ASSIGNED 1
#define sampleEvent__INTC_CORTEXM4_PRIORITY 7u
#define sampleEvent__INTC_NUMBER 124u
#define sampleEvent_INTC_CORTEXM4_ASSIGNED 1
#define sampleEvent_INTC_CORTEXM4_PRIORITY 7u
#define sampleEvent_INTC_NUMBER 124u

/* Batteri_ADC_IRQ */
#define Batteri_ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define Batteri_ADC_IRQ__INTC_CORTEXM4_PRIORITY 6u
#define Batteri_ADC_IRQ__INTC_NUMBER 138u
#define Batteri_ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define Batteri_ADC_IRQ_INTC_CORTEXM4_PRIORITY 6u
#define Batteri_ADC_IRQ_INTC_NUMBER 138u

/* BLE_PM_bless_isr */
#define BLE_PM_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_PM_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_PM_bless_isr__INTC_CORTEXM0P_PRIORITY 3u
#define BLE_PM_bless_isr__INTC_NUMBER 24u
#define BLE_PM_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_PM_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_PM_bless_isr_INTC_CORTEXM0P_PRIORITY 3u
#define BLE_PM_bless_isr_INTC_NUMBER 24u

/* I2C_MPU6050_SCB_IRQ */
#define I2C_MPU6050_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_MPU6050_SCB_IRQ__INTC_CORTEXM4_PRIORITY 6u
#define I2C_MPU6050_SCB_IRQ__INTC_NUMBER 47u
#define I2C_MPU6050_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_MPU6050_SCB_IRQ_INTC_CORTEXM4_PRIORITY 6u
#define I2C_MPU6050_SCB_IRQ_INTC_NUMBER 47u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
