/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_DIN */
#define Pin_DIN_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Pin_DIN_0_INBUF_ENABLED 1u
#define Pin_DIN_0_INIT_DRIVESTATE 0u
#define Pin_DIN_0_INIT_MUXSEL 0u
#define Pin_DIN_0_INPUT_SYNC 2u
#define Pin_DIN_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_DIN_0_NUM 0u
#define Pin_DIN_0_PORT GPIO_PRT0
#define Pin_DIN_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_DIN_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_DIN_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Pin_DIN_INBUF_ENABLED 1u
#define Pin_DIN_INIT_DRIVESTATE 0u
#define Pin_DIN_INIT_MUXSEL 0u
#define Pin_DIN_INPUT_SYNC 2u
#define Pin_DIN_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_DIN_NUM 0u
#define Pin_DIN_PORT GPIO_PRT0
#define Pin_DIN_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_DIN_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_SCK */
#define Pin_SCK_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_SCK_0_INBUF_ENABLED 0u
#define Pin_SCK_0_INIT_DRIVESTATE 0u
#define Pin_SCK_0_INIT_MUXSEL 0u
#define Pin_SCK_0_INPUT_SYNC 2u
#define Pin_SCK_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_SCK_0_NUM 1u
#define Pin_SCK_0_PORT GPIO_PRT0
#define Pin_SCK_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_SCK_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_SCK_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_SCK_INBUF_ENABLED 0u
#define Pin_SCK_INIT_DRIVESTATE 0u
#define Pin_SCK_INIT_MUXSEL 0u
#define Pin_SCK_INPUT_SYNC 2u
#define Pin_SCK_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_SCK_NUM 1u
#define Pin_SCK_PORT GPIO_PRT0
#define Pin_SCK_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_SCK_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 2u
#define UART_1_rx_0_PORT GPIO_PRT0
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 2u
#define UART_1_rx_PORT GPIO_PRT0
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 3u
#define UART_1_tx_0_PORT GPIO_PRT0
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 3u
#define UART_1_tx_PORT GPIO_PRT0
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Batteri_PIN */
#define Batteri_PIN_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Batteri_PIN_0_INBUF_ENABLED 0u
#define Batteri_PIN_0_INIT_DRIVESTATE 1u
#define Batteri_PIN_0_INIT_MUXSEL 0u
#define Batteri_PIN_0_INPUT_SYNC 2u
#define Batteri_PIN_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Batteri_PIN_0_NUM 2u
#define Batteri_PIN_0_PORT GPIO_PRT10
#define Batteri_PIN_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Batteri_PIN_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Batteri_PIN_DRIVEMODE CY_GPIO_DM_ANALOG
#define Batteri_PIN_INBUF_ENABLED 0u
#define Batteri_PIN_INIT_DRIVESTATE 1u
#define Batteri_PIN_INIT_MUXSEL 0u
#define Batteri_PIN_INPUT_SYNC 2u
#define Batteri_PIN_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Batteri_PIN_NUM 2u
#define Batteri_PIN_PORT GPIO_PRT10
#define Batteri_PIN_SLEWRATE CY_GPIO_SLEW_FAST
#define Batteri_PIN_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
