/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* WakeUp */
#define WakeUp__INTC_CORTEXM4_ASSIGNED 1
#define WakeUp__INTC_CORTEXM4_PRIORITY 7u
#define WakeUp__INTC_NUMBER 122u
#define WakeUp_INTC_CORTEXM4_ASSIGNED 1
#define WakeUp_INTC_CORTEXM4_PRIORITY 7u
#define WakeUp_INTC_NUMBER 122u

/* idleInt */
#define idleInt__INTC_CORTEXM4_ASSIGNED 1
#define idleInt__INTC_CORTEXM4_PRIORITY 7u
#define idleInt__INTC_NUMBER 123u
#define idleInt_INTC_CORTEXM4_ASSIGNED 1
#define idleInt_INTC_CORTEXM4_PRIORITY 7u
#define idleInt_INTC_NUMBER 123u

/* BLE_PM_bless_isr */
#define BLE_PM_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_PM_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_PM_bless_isr__INTC_CORTEXM0P_PRIORITY 3u
#define BLE_PM_bless_isr__INTC_NUMBER 24u
#define BLE_PM_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_PM_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_PM_bless_isr_INTC_CORTEXM0P_PRIORITY 3u
#define BLE_PM_bless_isr_INTC_NUMBER 24u

/* I2C_MPU6050_SCB_IRQ */
#define I2C_MPU6050_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_MPU6050_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_MPU6050_SCB_IRQ__INTC_NUMBER 47u
#define I2C_MPU6050_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_MPU6050_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_MPU6050_SCB_IRQ_INTC_NUMBER 47u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
