/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* isr_timer */
#define isr_timer__INTC_CORTEXM4_ASSIGNED 1
#define isr_timer__INTC_CORTEXM4_PRIORITY 7u
#define isr_timer__INTC_NUMBER 122u
#define isr_timer_INTC_CORTEXM4_ASSIGNED 1
#define isr_timer_INTC_CORTEXM4_PRIORITY 7u
#define isr_timer_INTC_NUMBER 122u

/* sampleEvent */
#define sampleEvent__INTC_CORTEXM4_ASSIGNED 1
#define sampleEvent__INTC_CORTEXM4_PRIORITY 7u
#define sampleEvent__INTC_NUMBER 123u
#define sampleEvent_INTC_CORTEXM4_ASSIGNED 1
#define sampleEvent_INTC_CORTEXM4_PRIORITY 7u
#define sampleEvent_INTC_NUMBER 123u

/* UART_1_SCB_IRQ */
#define UART_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ__INTC_NUMBER 46u
#define UART_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ_INTC_NUMBER 46u

/* Batteri_ADC_IRQ */
#define Batteri_ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define Batteri_ADC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define Batteri_ADC_IRQ__INTC_NUMBER 138u
#define Batteri_ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define Batteri_ADC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define Batteri_ADC_IRQ_INTC_NUMBER 138u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
